FROM python:3.6-slim
MAINTAINER Robert Dempsey <robertonrails@gmail.com>

# Install OS requirements
ENV PYTHONBUFFERED 1
RUN apt-get update -y -qq

# Install the requirements
COPY requirements.txt /tmp/
RUN pip install -r /tmp/requirements.txt

# Set up the code directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Copy over the code
COPY jobber/web web/
COPY tests tests/

# Run that beautiful Jobber Web
CMD ["python", "web/jobber.py"]