FROM python:3.6-slim
MAINTAINER Robert Dempsey <robertonrails@gmail.com>

# Install OS requirements
ENV PYTHONBUFFERED 1
RUN apt-get update && apt-get -y install gcc

# Set up the code directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Copy over the code
COPY jobber/api api/
COPY tests tests/

# Install the requirements
RUN pip install -r api/requirements.txt

# Run that beautiful Jobber API
CMD ["python", "api/jobber.py"]