FROM python:3.6-slim
MAINTAINER Robert Dempsey <robertonrails@gmail.com>

# Install OS requirements
ENV PYTHONBUFFERED 1
RUN apt-get update -y -qq

# Set up the code directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Copy over the code
COPY jobber/web web/
COPY tests tests/

# Install the requirements
RUN pip install -r web/requirements.txt

# Run that beautiful Jobber Web aoo
CMD ["python", "web/jobber.py"]